### ISSUE TITLE
wordpress in a subdirectory

### ISSUE THREAD

**Issue by hookedgeardev** [enderandpeter/wpgithooks#2]
I have my wordpress in a subdirectory with only index.php and .htaccess in the root. Can the script be modified to work with this?

edit: I think just pointing it to the subdirectory is okay

**Comment by enderandpeter** [comment]
Oh my goodness. I did not think anyone in the world cared about this. Yes, please let me know if you run into trouble!

**Comment by hookedgeardev** [comment]
It's exactly what I was looking for, and it's going to save me a lot of time and trouble. Thank you so much for making it.
